spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/banking-service

keycloak.server-url=http://localhost:8080
keycloak.realm=banking-service
keycloak.client-id=banking-auth-service
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}


#management.endpoints.web.exposure.include=health,info